name: ElementalFactions
version: 4.1.5
main: com.nate.elemental.Factions
author: NatesHonor
website: https://inate.xyz
description: A Factions plugin Designed for Elemental Legacy
api-version: 1.17
commands:
  f:
    description: Default factions command
    usage: /f help
  f help:
    description: Displays the help messages
    usage: /f help
  f show:
    description: Shows information on a faction
    usage: /f show <faction> (optional)
  f create:
    description: Creates a new faction
    usage: /f create <faction>
  f desc:
    description: Shows information on a faction
    usage: /f show <faction> (optional)
  f accept:
    description: Shows information on a faction
    usage: /f show <faction> (optional)
  f ally:
    description: Shows information on a faction
    usage: /f show <faction> (optional)
  f claim:
    description: Shows information on a faction
    usage: /f show <faction> (optional)
  f enemy:
    description: Shows information on a faction
    usage: /f show <faction> (optional)
  f invite:
    description: Shows information on a faction
    usage: /f show <faction> (optional)
  horse: 
    description: Opens the Horse GUI
    usage: /horse
  elixir:
    description: Opens the elixir shop
    usage: /elixir
  raidshop:
    description: Opens the Raid Shop
    usage: /raidshop
  spawnershop:
    description: Opens the Spawner Shop
    usage: /spawnershop
  trenchpickaxe:
    description: Gives a user a trench pickaxe
    usage: /trenchpickaxe
  debug-h2:
    description: Debug an h2 Table
    usage: /debug-h2 table
  genbukkit:
    description: Opens the genbukkit shop
    usage: /genbukkit